datasource:
  master:
    url: jdbc:mysql://192.168.137.128:3306/babycheck?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 20
    initial-size: 1
    max-wait: 6000
    pool-prepared-statements: true
    max-open-prepared-statements: 20
  slave:
    url: jdbc:mysql://192.168.137.128:3306/babycheck?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 20
    initial-size: 1
    max-wait: 6000
    pool-prepared-statements: true
    max-open-prepared-statements: 20
server:
  port: 7000

spring:
  application:
    name: guyueweb
  profiles:
    active: local